#!/bin/sh /etc/rc.common
# Make the xupnpd service follow the "enabled" option in /etc/config/xupnpd.
# The xupnpd package ships its own init script, which ignores UCI.

START=51
USE_PROCD=1

xupnpd_sync() {
	local enabled

	config_load "xupnpd"
	config_get_bool enabled config enabled 0

	if [ "$enabled" -eq 1 ]; then
		/etc/init.d/xupnpd enable
		/etc/init.d/xupnpd "${1:-start}"
	else
		/etc/init.d/xupnpd disable
		/etc/init.d/xupnpd stop
	fi
}

start_service() {
	xupnpd_sync start
}

reload_service() {
	xupnpd_sync restart
}

service_triggers() {
	procd_add_reload_trigger "xupnpd"
}
